### ISSUE TITLE
Error when npm install

### ISSUE THREAD

**Issue by yuliantosb** [PacktPublishing/Full-Stack-Vue.js-2-and-Laravel-5#11]
Hello sir, I've been follow your book instruction, but I get stuck when install npm, 
the error like this

![screenshot from 2018-03-14 21 13 05](https://user-images.githubusercontent.com/16331964/37407661-c8607ff6-27cc-11e8-9302-ca56c74a78e7.png)

I'm new using npm and webpack and other stuff like that, can you give me some advice? I have searching on google and also ask in stackoverflow but has no answer yet, still error like that. Thanks for your answer, sorry for my bad English, I'm on chapter 5 anyway

**Comment by yuliantosb** [comment]
Mr. Gore, please help me :cry:

**Comment by anthonygore** [comment]
Hi, looks like node-sass is failing to install. This thread might help: https://github.com/sass/node-sass/issues/1098

node-sass is notorious for causing problems so I'd suggest you look into that more.
