### ISSUE TITLE
Adding amenities value

### ISSUE THREAD

**Issue by meeglos** [PacktPublishing/Full-Stack-Vue.js-2-and-Laravel-5#14]
I'm trying to change the way amenities are displayed, based on their availability (the table's true or false value).
This value is not included once the **populateAmenitiesAndPrices (in helpers.js)** function returns the object.
So, what would be the best way to include this "status" value in the object?

**Comment by anthonygore** [comment]
Sorry for the late reply.

There was a bug regarding the amenities that was recently fixed by one of the readers. See here: https://github.com/PacktPublishing/Full-Stack-Vue.js-2-and-Laravel-5/pull/10

Does that solve your issue?

**Comment by meeglos** [comment]
Hi Anthony!
Yes, that should solve my issue, I made a different approach though.
Great book, thanks!
