### ISSUE TITLE
Typos in Chapter 2

### ISSUE THREAD

**Issue by drdan18** [PacktPublishing/Full-Stack-Vue.js-2-and-Laravel-5#15]
I am very new to Vue, which is why I bought this book.  From what I can tell the following has errors in it and it does not reflect the source file it refers to.   This is from page 31 of the PDF and it is the same in the online version at packtpub.com.  

> Vue has dominion over the element it mounts on and any child node. For our project so far,
Vue could manipulate the div with the header class, but it could not manipulate
the div with the toolbar ID. Anything placed within this latter div will be invisible to
Vue.
index.html:
```HTML
<body>
<div id="toolbar">...</div>
<div id="app">
<!--Vue only has dominion here-->
<div class="header">...</header>
...
</div>
<script src="node_modules/vue/dist/vue.js"></script>
<script src="app.js"></script>
</body>
```

In this example code given the div that has a header class is closed with a `</header>` tag, which doesn't make sense to me.  It is also completely different from the actual code in the index.html file, which is the following: 

```html
<body>
<div id="toolbar">
  <img class="icon" src="logo.png">
  <h1>vuebnb</h1>
</div>
<div id="app">
  <div class="container"></div>
</div>
<script src="app.js"></script>
</body>
```

There is no div with a class called header.  The class is called container.  I am confused enough.  These typos don't help.

**Comment by anthonygore** [comment]
Yeah, you're right, that code snippet should be:

```html
<body>
<div id="toolbar">...</div>
<div id="app">
  <!--Vue only has dominion here-->
  <div class="container">...</div>
  ...
</div>
<script src="node_modules/vue/dist/vue.js"></script>
<script src="app.js"></script>
</body>
```

**Comment by drdan18** [comment]
Yes, and the text should be referring to the container class, not the header class. 

I am happy to report I am now part way through Chapter 4 and I have found no more typos.   Enjoying the process so far.
