### ISSUE TITLE
Chapter 09 Passport API Auth problem

### ISSUE THREAD

**Issue by mlgrozev** [PacktPublishing/Full-Stack-Vue.js-2-and-Laravel-5#17]
Hi Anthony, I had a problem with chapter 09.

I went through all chapter in your books happily, but I got a problem with Authentication with Passport in chapter 9.

I always got error: 
(POST) api/user/toggle_saved 401 (Unauthorized) 
I checked carefully about your step-by-step in your book.
I tried to do a google search, but I couldn't solve this problem.
Finally, I need your support.

I hope you can spend your time to help me about this issue.

Thank you so much in advanced!

**Comment by anthonygore** [comment]
Hey, sorry for the late reply.

Can you link me to your codebase so I can see?

**Comment by elinardo10** [comment]
Hi, me to with error too... In docs of laravel they say to do this: **php artisan vendor:publish --tag=passport-components**, 
but in your book you don't said about. Another questions: the 'saved' state comes with user login in dinamic mode ya?

**Comment by anthonygore** [comment]
You don't need the Vue components in my tutorial so no need for `--tag=passport-components`

**Comment by phamhuutruong7** [comment]
Hi Anthony, I have the same problem too. 
I don't know why would you want to make OAuth when making saved items. I tried to search but I don't think that the other would use OAuth through API to make saved list. 
As I understand, when I create a new User, a "authorization code" will be granted. This will be written in table oauth_clients with client_id, name, secret. 
Each "client" is like a web site that connects to the website's data. (Matt Stauffer wrote that on his website.)(https://mattstauffer.com/blog/introducing-laravel-passport/)
In this situation here, the secret gonna be my access-token, is that right?
