### ISSUE TITLE
Book and source code not in sync for data migrations

### ISSUE THREAD

**Issue by bartonhammond** [PacktPublishing/Full-Stack-Vue.js-2-and-Laravel-5#18]
In chapter 4, the book says there is a file `2017_06_20_133317_create_listings_table.php` in the `database/migrations`.  But there is no file w/ that name.

**Comment by anthonygore** [comment]
When you create a Laravel migration the file has a timestamp at the beginning e.g. `2017_06_20_133317`. This is to ensure the migrations always get run in order. So when you attempt to create a migration, yours will be the same file name as mine, only the timestamp will be different. Read more here https://laravel.com/docs/5.6/migrations
