### ISSUE TITLE
page 88 / typo amenity_wifi

### ISSUE THREAD

**Issue by vjardin** [PacktPublishing/Full-Stack-Vue.js-2-and-Laravel-5#24]
Page 88, it is stated for the example:

> `echo gettype($listing->amenity_wifi());
`

it should be:

`echo gettype($listing->amenity_wifi);
`

For example:
```php
$ php artisan tinker
>>> $listings = \App\Listing::all();
>>> foreach ($listings as $listing) { 
   echo $listing->address . '\n';
  echo gettype($listing->amenity_wifi);
}
```

**Comment by deepesh-packt** [comment]
Hi @vjardin 
 Please reopen if the issue still persists.
