### ISSUE TITLE
Typo in chapter2:event modifiers

### ISSUE THREAD

**Issue by patlecat** [PacktPublishing/Full-Stack-Vue.js-2-and-Laravel-5#4]
There should not be a `</span>` in the function parameters!

```javascript
document.addEventListener(</span>'keyup', function(evt) {
if (evt.keyCode === 27 && app.modalOpen) {
app.modalOpen = false;
}
});
```

**Comment by anthonygore** [comment]
Thanks for reporting this

**Comment by patlecat** [comment]
Actually there's more "dead HTML" code in samples as well all over the book

**Comment by anthonygore** [comment]
Yeah. Unfortunately there was a bug in the publisher's software and these seemingly random formatting artifacts were added to the code. I believe these are all removed from the digital versions of the book now, so if you have an eBook, redownload it and they'll be gone.
