### ISSUE TITLE
HeaderComponent call open modal 

### ISSUE THREAD

**Issue by alphyon** [PacktPublishing/Full-Stack-Vue.js-2-and-Laravel-5#8]
try the code with the explain, in the momenent to trigger event click to launch the modal obtain the next warning

[Vue warn]: Error in event handler for "header-clicked": "TypeError: Cannot set property 'modalOpen' of undefined"
found in
---> <HeaderImage> at resources/assets/components/HeaderImage.vue
       <Root>

I try change or send the property but I dont understand with this issue, thank for help me

**Comment by alphyon** [comment]
hi @anthonygore this is the link to my code 
https://github.com/alphyon/Full-Stack-Vue.js-2-and-Laravel-5
thanks for your help

**Comment by anthonygore** [comment]
I don't think you've made any commits to this code. You need to ensure that your changes are committed and pushed to the repo.

**Comment by alphyon** [comment]
sorry man this is the link with mi code https://github.com/alphyon/vuebnbn

**Comment by anthonygore** [comment]
You have a typo in *resources/views/app.blade.php*. `<modal-window ref="imagemodel">` should be <modal-window ref="imagemodal">
