### ISSUE TITLE
Chapter5 error npm install

### ISSUE THREAD

**Issue by ecyberweb** [PacktPublishing/Full-Stack-Vue.js-2-and-Laravel-5#9]
Hi there,

I'm on chapter 5 and getting this error when run npm install (tried with sudo as well):

vagrant@homestead:~/projects/vuebnb$ npm install
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: assert-plus@1.0.0 (node_modules/fsevents/node_modules/dashdash/node_modules/assert-plus):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, open '/home/vagrant/projects/vuebnb/node_modules/fsevents/node_modules/dashdash/node_modules/assert-p
lus/package.json.1682293961'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: assert-plus@1.0.0 (node_modules/fsevents/node_modules/getpass/node_modules/assert-plus):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, open '/home/vagrant/projects/vuebnb/node_modules/fsevents/node_modules/getpass/node_modules/assert-pl
us/package.json.4177708995'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: assert-plus@1.0.0 (node_modules/fsevents/node_modules/sshpk/node_modules/assert-plus):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, open '/home/vagrant/projects/vuebnb/node_modules/fsevents/node_modules/sshpk/node_modules/assert-plus
/package.json.685348660'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: minimist@1.2.0 (node_modules/fsevents/node_modules/rc/node_modules/minimist):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, open '/home/vagrant/projects/vuebnb/node_modules/fsevents/node_modules/rc/node_modules/minimist/packa
ge.json.507977674'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: assert-plus@1.0.0 (node_modules/fsevents/node_modules/jsprim/node_modules/assert-plus):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, open '/home/vagrant/projects/vuebnb/node_modules/fsevents/node_modules/jsprim/node_modules/assert-plu
s/package.json.328223166'

npm ERR! path ../acorn/bin/acorn
npm ERR! code EPROTO
npm ERR! errno -71
npm ERR! syscall symlink
npm ERR! EPROTO: protocol error, symlink '../acorn/bin/acorn' -> '/home/vagrant/projects/vuebnb/node_modules/.bin/acorn'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2018-03-05T17_01_12_688Z-debug.log

**Comment by anthonygore** [comment]
Can you paste the full log from /home/vagrant/.npm/_logs/2018-03-05T17_01_12_688Z-debug.log

**Comment by ecyberweb** [comment]
I solved this problem grabbing some hints from two threads:

1) downgrading my npm to 5.5.1 -  npm install -g npm@~5.5.0
2) installing - npm install ajv@^6.0.0 [https://github.com/angular/angular-cli/issues/9691]
3) running as administrator in cmd windows 10 the command - npm install [https://github.com/laravel/homestead/issues/611]

Done that I could run - npm run dev - and the things worked very well.

But I suppose that only the third instruction is that properly helped, but anyway, it's working.

Let's move on to next chapters!

Thank you very much for replying too soon, Anthony.

**Comment by ecyberweb** [comment]
Hi,

Just posting it to help someone who might go through the same issues. 

In order to Migrating, removing unnecessary dependencies, I had to do what follows:

1) removing my current npm version 5.5.1 - sudo apt-get purge nodejs npm
2) installing the 5.6 npm version 
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs

And that's it, now the command - npm uninstall bootstrap-sass jquery lodash --save-dev - works very well. Being aware of I'm running the cmd as an administrator.

Thanks.

**Comment by ecyberweb** [comment]
I've had to add --watch-poll " after --watch in the package.json in order the command - npm run watch - works properly. ("watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --watch-poll --progress --display-modules --config=node_modules/laravel-mix/setup/webpack.config.js",)

**Comment by ecyberweb** [comment]
On chapter 6, in order to correct the **Vue packages version mismatch issue**, I had to reinstall the vue-template-compiler as well as vue, as follow: 

1. `npm uninstall vue-template-compiler`
2. `npm install vue-template-compiler`
3. `npm install vue`
